// vue-js/src/App.vue
<script setup>
import { computed, onMounted, ref } from 'vue';

const apiBase = import.meta.env.VITE_API_BASE_URL || '';

const authLoading = ref(true);
const authError = ref('');
const user = ref(null);
const name = ref('');
const containsName = ref(false);
const searchLoading = ref(false);
const searchError = ref('');
const count = ref(null);

const isSignedIn = computed(() => Boolean(user.value));
const displayName = computed(() => user.value?.name || user.value?.email || 'Signed in');

onMounted(() => {
  loadCurrentUser();
});

async function loadCurrentUser() {
  authLoading.value = true;
  authError.value = '';

  try {
    const response = await fetch(`${apiBase}/auth/me`, {
      credentials: 'include'
    });
    const data = await response.json();
    user.value = response.ok && data.authenticated ? data.user : null;
  } catch (err) {
    authError.value = 'Could not load sign-in state.';
    user.value = null;
  } finally {
    authLoading.value = false;
  }
}

function signInWithGoogle() {
  window.location.href = `${apiBase}/auth/google`;
}

async function logout() {
  authLoading.value = true;
  authError.value = '';

  try {
    const response = await fetch(`${apiBase}/auth/logout`, {
      method: 'POST',
      credentials: 'include'
    });
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    user.value = null;
  } catch (err) {
    authError.value = 'Could not sign out.';
  } finally {
    authLoading.value = false;
  }
}

async function findPasuk() {
  const trimmedName = name.value.trim();
  count.value = null;
  searchError.value = '';

  if (trimmedName.length <= 1) {
    searchError.value = 'Enter at least two characters.';
    return;
  }

  searchLoading.value = true;
  try {
    const url = new URL(`${apiBase}/psukim`, window.location.origin);
    url.searchParams.set('name', trimmedName);
    url.searchParams.set('containsName', String(containsName.value));

    const response = await fetch(url, {
      credentials: 'include'
    });
    const data = await response.json();
    if (!response.ok) throw new Error(data.error || `HTTP ${response.status}`);
    count.value = data.count;
  } catch (err) {
    searchError.value = 'Could not search psukim.';
  } finally {
    searchLoading.value = false;
  }
}
</script>

<template>
  <main class="app-shell">
    <section class="topbar" aria-label="Account">
      <div>
        <p class="eyebrow">Heb Bible</p>
        <h1>Pasuk Finder</h1>
      </div>

      <div class="account">
        <div v-if="authLoading" class="status-text">Checking account...</div>
        <template v-else-if="isSignedIn">
          <img v-if="user.picture" class="avatar" :src="user.picture" alt="">
          <div class="account-name">
            <span>{{ displayName }}</span>
            <small v-if="user.email">{{ user.email }}</small>
          </div>
          <button class="secondary-button" type="button" @click="logout">Sign out</button>
        </template>
        <button v-else class="google-button" type="button" @click="signInWithGoogle">
          <span class="google-mark" aria-hidden="true">G</span>
          Sign in with Google
        </button>
      </div>
    </section>

    <p v-if="authError" class="error-message">{{ authError }}</p>

    <section class="tool-panel" aria-label="Pasuk search">
      <form class="search-form" @submit.prevent="findPasuk">
        <label for="name">Name</label>
        <div class="input-row">
          <input
            id="name"
            v-model="name"
            type="text"
            autocomplete="name"
            dir="auto"
            placeholder="Enter a Hebrew name"
          >
          <button type="submit" :disabled="searchLoading">
            {{ searchLoading ? 'Searching...' : 'Find Pasuk' }}
          </button>
        </div>

        <label class="checkbox-row">
          <input v-model="containsName" type="checkbox">
          <span>Match verses containing the full name</span>
        </label>
      </form>

      <div class="result-area" aria-live="polite">
        <p v-if="searchError" class="error-message">{{ searchError }}</p>
        <p v-else-if="count !== null" class="result-count">
          {{ count }} matching psukim
        </p>
        <p v-else class="muted">Search results will appear here.</p>
      </div>
    </section>
  </main>
</template>

// react-sb/src/App.jsx
import { useEffect, useRef, useState } from 'react';
import {
  authenticate,
  countPsukim,
  currentUser,
  googleLoginUrl,
  setToken,
  signOut
} from './api.js';

function EmailAuthDialog({ onAuthenticated, onClose }) {
  const [mode, setMode] = useState('login');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const emailInput = useRef(null);

  useEffect(() => {
    emailInput.current?.focus();

    function closeOnEscape(event) {
      if (event.key === 'Escape') onClose();
    }

    window.addEventListener('keydown', closeOnEscape);
    return () => window.removeEventListener('keydown', closeOnEscape);
  }, [onClose]);

  async function handleSubmit(event) {
    event.preventDefault();
    setError('');
    setSubmitting(true);

    try {
      const user = await authenticate(mode, email.trim(), password);
      onAuthenticated(user);
    } catch (requestError) {
      setError(requestError.message);
    } finally {
      setSubmitting(false);
    }
  }

  function changeMode(nextMode) {
    setMode(nextMode);
    setError('');
  }

  return (
    <div className="dialog-backdrop" onMouseDown={onClose}>
      <section
        aria-labelledby="auth-title"
        aria-modal="true"
        className="auth-dialog"
        onMouseDown={(event) => event.stopPropagation()}
        role="dialog"
      >
        <button
          aria-label="Close email sign in"
          className="dialog-close"
          onClick={onClose}
          type="button"
        >
          ×
        </button>

        <p className="eyebrow">Your account</p>
        <h2 id="auth-title">
          {mode === 'login' ? 'Welcome back' : 'Create an account'}
        </h2>
        <p className="dialog-copy">
          {mode === 'login'
            ? 'Sign in with the email you registered.'
            : 'Use an email and a password of at least 8 characters.'}
        </p>

        <div className="mode-switch" aria-label="Email authentication option">
          <button
            aria-pressed={mode === 'login'}
            onClick={() => changeMode('login')}
            type="button"
          >
            Sign in
          </button>
          <button
            aria-pressed={mode === 'signup'}
            onClick={() => changeMode('signup')}
            type="button"
          >
            Register
          </button>
        </div>

        <form className="auth-form" onSubmit={handleSubmit}>
          <label htmlFor="email">Email</label>
          <input
            autoComplete="email"
            id="email"
            onChange={(event) => setEmail(event.target.value)}
            ref={emailInput}
            required
            type="email"
            value={email}
          />

          <label htmlFor="password">Password</label>
          <input
            autoComplete={mode === 'login' ? 'current-password' : 'new-password'}
            id="password"
            maxLength="100"
            minLength="8"
            onChange={(event) => setPassword(event.target.value)}
            required
            type="password"
            value={password}
          />

          {error && <p className="form-error" role="alert">{error}</p>}

          <button className="primary-button auth-submit" disabled={submitting} type="submit">
            {submitting
              ? 'Please wait…'
              : mode === 'login'
                ? 'Sign in'
                : 'Create account'}
          </button>
        </form>
      </section>
    </div>
  );
}

export default function App() {
  const [user, setUser] = useState(null);
  const [checkingAuth, setCheckingAuth] = useState(true);
  const [showEmailAuth, setShowEmailAuth] = useState(false);
  const [name, setName] = useState('');
  const [count, setCount] = useState(null);
  const [error, setError] = useState('');
  const [searching, setSearching] = useState(false);

  useEffect(() => {
    let active = true;

    currentUser()
      .then((signedInUser) => {
        if (active) setUser(signedInUser);
      })
      .catch(() => {
        setToken(null);
      })
      .finally(() => {
        if (active) setCheckingAuth(false);
      });

    return () => {
      active = false;
    };
  }, []);

  async function handleSearch(event) {
    event.preventDefault();
    const trimmedName = name.trim();
    setCount(null);
    setError('');

    if (trimmedName.length < 2) {
      setError('Enter at least two characters.');
      return;
    }
    if (!user) {
      setError('Please sign in before searching.');
      return;
    }

    setSearching(true);
    try {
      setCount(await countPsukim(trimmedName));
    } catch (requestError) {
      setError(requestError.message);
    } finally {
      setSearching(false);
    }
  }

  async function handleSignOut() {
    await signOut();
    setUser(null);
    setCount(null);
    setError('');
  }

  const userLabel = user?.email || user?.name;

  return (
    <main className="page-shell">
      <div className="ambient ambient-one" />
      <div className="ambient ambient-two" />

      <section className="app-card">
        <header className="topbar">
          <a className="brand" href="/" aria-label="Heb Bible home">
            <span className="brand-mark" aria-hidden="true">א</span>
            <span>Heb Bible</span>
          </a>

          {!checkingAuth && user && (
            <div className="signed-in">
              <span title={userLabel}>{userLabel}</span>
              <button onClick={handleSignOut} type="button">Sign out</button>
            </div>
          )}
        </header>

        <div className="hero">
          <div className="ornament" aria-hidden="true">
            <span />
            <b>׃</b>
            <span />
          </div>
          <p className="eyebrow">A name in the text</p>
          <h1>Count the verses.</h1>
          <p className="intro">
            Enter a Hebrew name to discover how many biblical verses match it.
          </p>

          {!checkingAuth && !user && (
            <div className="auth-actions" aria-label="Sign in options">
              <a className="google-button" href={googleLoginUrl()}>
                <span className="google-mark" aria-hidden="true">G</span>
                Continue with Google
              </a>
              <button
                className="email-button"
                onClick={() => setShowEmailAuth(true)}
                type="button"
              >
                Sign in or register
              </button>
            </div>
          )}

          {checkingAuth && <p className="checking-auth">Checking your account…</p>}

          <form className="search-form" onSubmit={handleSearch}>
            <label htmlFor="name">Hebrew name</label>
            <div className="search-row">
              <input
                autoComplete="name"
                dir="auto"
                id="name"
                onChange={(event) => setName(event.target.value)}
                placeholder="למשל, שחר"
                type="text"
                value={name}
              />
              <button className="primary-button" disabled={searching} type="submit">
                {searching ? 'Counting…' : 'Count verses'}
              </button>
            </div>
          </form>

          <div className="result" aria-live="polite">
            {error && <p className="result-error" role="alert">{error}</p>}
            {count !== null && !error && (
              <>
                <strong>{count.toLocaleString()}</strong>
                <span>{count === 1 ? 'matching verse' : 'matching verses'}</span>
              </>
            )}
            {count === null && !error && (
              <p className="result-hint">
                {user ? 'Your result will appear here.' : 'Sign in, then enter a name to begin.'}
              </p>
            )}
          </div>
        </div>

        <footer>
          <span aria-hidden="true">✦</span>
          <p>Search the Hebrew Bible by name</p>
          <span aria-hidden="true">✦</span>
        </footer>
      </section>

      {showEmailAuth && (
        <EmailAuthDialog
          onAuthenticated={(signedInUser) => {
            setUser(signedInUser);
            setShowEmailAuth(false);
            setError('');
          }}
          onClose={() => setShowEmailAuth(false)}
        />
      )}
    </main>
  );
}
